name: kebs_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+25

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.3.8
  gap: ^2.0.1
  carousel_slider: ^4.2.1
  http:
  url_launcher: ^6.1.9
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  connectivity_widget: ^1.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  image_picker: ^0.8.7
  mailer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_automation: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: 'assets/logo.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
